## to read all data needed

### 1. read merchindise export data, annual by HS L4 code and country
## This data is generated by the Sectors report project, inlcuded in the Sectors Database in PlayPen (SDdb)
#dtf_ex_country_yr <-
#   sr_get_dataset("New Zealand Goods and Services Exports by Country",db_location = 'server')
load(paste0(output_folder,"/Exports_shiny.rda"))

### 2. read merchindise import data, annual by HS L4 code and country
## This data is generated by the Sectors report project, inlcuded in the Sectors Database in PlayPen (SDdb)
#dtf_im_country_yr <-
#   sr_get_dataset("New Zealand Goods and Services Imports by Country",db_location = 'server')
load(paste0(output_folder,"/Imports_shiny.rda"))

### 3. Total goods and services export and import data, qtr long term
# dtf_trade_tot <-
#    ImportTS2(TRED,
#              Dataset ="BPM6 Quarterly, Balance of payments major components (Qrtly-Mar/Jun/Sep/Dec)",
#              where = " (CV1 = 'Actual') and (CV2 IN ('Current account; Goods; Exports (fob) total' , 'Current account; Goods; Imports (fob) total' , 'Current account; Services; Exports total' , 'Current account; Services; Imports total') )"
#              )

## or just download .csv file and read there
load("data_intermediate/dtf_snz_total.rda")

dtf_trade_tot <-
   read.csv(file_total_goods_services) %>%
   gather( CV2, Value, -TimePeriod ) %>%
   dplyr::mutate( TimePeriod = as.character(TimePeriod),
           TimePeriod = as.yearqtr(as.character(TimePeriod), '%YQ%q' )  ,
           TimePeriod = as.Date( TimePeriod , frac = 1)
           ) %>%
   dplyr::mutate( CV2 = gsub("Current.account..Goods..Exports..fob..total",
                      'Current account; Goods; Exports (fob) total',
                      CV2),
           CV2 = gsub("Current.account..Services..Exports.total",
                      'Current account; Services; Exports total',
                      CV2),
           CV2 = gsub("Current.account..Goods..Imports..fob..total",
                      'Current account; Goods; Imports (fob) total',
                      CV2),
           CV2 = gsub("Current.account..Services..Imports.total",
                      'Current account; Services; Imports total',
                      CV2)
           )

## 
dtf_trade_tot_old <- 
   dtf_trade_tot %>% 
   filter( as.yearqtr(TimePeriod) <= as.yearqtr("2014 Q1")  )


dtf_trade_tot <- 
   dtf_trade_tot_old %>% 
   bind_rows( arrange(dtf_snz_total, TimePeriod) )

## or derive from coutry level data when the most recent update is not available
# tmp_max_q <- unique(dtf_ex_country_yr$Sector )
# 
# if( as.yearqtr(max(dtf_trade_tot$TimePeriod)) != 
#     paste0(max(dtf_ex_country_yr$Year), " ", substr( tmp_max_q , nchar(tmp_max_q)-1 ,nchar(tmp_max_q) ) ) ){
#    
#    Tot_From_Country <- TRUE ## total trade calculated from total
#    
#    tmp_dtf_ex_s_tot <- 
#       dtf_ex_country_yr %>%
#       filter( Dimension1 == "Total services" ) %>%
#       group_by( Year, Dimension1 ) %>%
#       summarise( Value = sum( Value, na.rm = T) ) %>%
#       ungroup
#    
# }


## 4. read full Services trade by country using this source: https://www.stats.govt.nz/information-releases/goods-and-services-trade-by-country-year-ended-march-2018 --------
## Note: the Goods and services trade by country: Year ended March 2018 – map data CSV data contains service trade by all countries !!
## One to manually search the data from internet and then download the data and save it to the data_raw folderd
#tmp_file <- "goods-and-services-trade-by-country-year-ended-march-2018-map-data-csv.csv" ## you need to change the file every update
#tmp_file <- "goods-services-trade-by-country-june-2018-map-data.csv" 
#tmp_file <- "goods-services-trade-by-country-jun18-map-data-csv-corrected.csv" ## Due to StatsNZ's correction on 3 Oct
#tmp_file <- "goods-and-services-trade-by-country-year-ended-september-2018-map-data-csv.csv"
#tmp_file <- "goods-and-services-trade-by-country-year-ended-december-2018-map-data-csv.csv"
#
#dtf_trade_country_snz <- read.csv( paste0("data_raw/",tmp_file) )
dtf_trade_country_snz <- read.csv( file_map_goods_services_by_country )


### Test if max quarter are the same for tot and by commodity
tmp_max_q <- unique(dtf_ex_country_yr$Sector)
tmp_max_q <- substr(tmp_max_q , nchar(tmp_max_q)-1,  nchar(tmp_max_q))

tmp_max_q_tot <- as.character(as.yearqtr( max(dtf_trade_tot$TimePeriod )))
tmp_max_q_tot <- substr(tmp_max_q_tot , nchar(tmp_max_q_tot)-1,  nchar(tmp_max_q_tot))

tmp_max_q_snz <- unique( substr(dtf_trade_country_snz$Time_ref,6,7) )
if( tmp_max_q_snz == '03' ) tmp_max_q_snz <- 'Q1'
if( tmp_max_q_snz == '06' ) tmp_max_q_snz <- 'Q2'
if( tmp_max_q_snz == '09' ) tmp_max_q_snz <- 'Q3'
if( tmp_max_q_snz == '12' ) tmp_max_q_snz <- 'Q4'

if( tmp_max_q != tmp_max_q_tot ){
   stop("The ended quarter is different between total and by country/commodity. Pls update the data.")
   rm('dtf_ex_country_yr')
   rm('dtf_im_country_yr')
   rm('dtf_trade_tot')
}

# else{
#    if( tmp_max_q_snz != tmp_max_q){
#       stop("The ended quarter is different between total and by country/commodity, and service trade by country. Pls update the data.")
#       rm('dtf_trade_country_snz')
#    }
# }
